### PR TITLE
fix #156: Removed early return for useConfig so applyHead can be set on ssr=false.

### LINKED ISSUE #156: [bug] useConfig does not work on the clientside (only on vike-solid)
I discovered this accidentally while doing `ssr: false` for the page. That assumes every code is ran on the clientside. Surprisingly, useConfig does not set anything on the clientside. There might be something that needs to be fixed in vike-solid's implementation of this.

Repro links:

SolidJS
https://stackblitz.com/edit/m1gu2syi?file=pages%2Fnossr%2F%2BPage.tsx

React - it's fine here. No problems.
https://stackblitz.com/edit/r45stpep?file=pages%2Fnossr%2F%2BPage.tsx

(I'm also looking into this)

### PR DESCRIPTION
**Pull request by Blankeos**
This fixes https://github.com/vikejs/vike-solid/issues/156.

The expected result is that the `title` and `lang` is set even during `ssr: false`.

## Before the fix.
I think the reason why `title` and `lang` were not set during `ssr: false` is because in SolidJS, generally every component/hook runs only once. So early returns are discouraged because you will always get the first returned thing as it never re-runs the whole function.

Considering that, on the initial render on the client-side, `let pageContext = getPageContext() as PageContext & PageContextInternal;` exists so the function returned by the hook everytime is `() => setPageContextConfigFromHook(config, pageContext);` (which does not call `applyHead`).

`applyHead` is what sets the `title` and `lang`.

## The fix

Here, the returned function from the hook is always the same function which I think fixes the problem.
Also, unlike React, SolidJS can have "hooks" anywhere like inside an if statement, inside another hook's callback, etc. That's why you can see I'm using `usePageContext()` even inside an if statement.

### CODE REVIEW

File: packages/vike-solid/hooks/useConfig/useConfig-client.ts [hunk 1]
```diff
@@ -10,20 +10,20 @@ import { applyHeadSettings } from "../../integration/applyHeadSettings.jsx";
...
       setPageContextConfigFromHook(config, pageContext);
     } else {
-      applyHead(config);
+      if (typeof window !== 'undefined') applyHead(config);
     }
   };
 }
 
 function setPageContextConfigFromHook(config: ConfigFromHook, pageContext: PageContextInternal) {
+  console.log("setting page context config from hook.", config)
```
Comment (magne4000) [inline packages/vike-solid/hooks/useConfig/useConfig-client.ts:26]:
```suggestion
```

**Review by magne4000 — APPROVED** [review]
